workspace = { members = [ "naive_bayes","rss-sync"] }
[package]
name = "rustlefeed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = {version = "^1.36.0", features = ["full"]}
rss-sync = { path = "./rss-sync" }
